#!/usr/bin/env zsh

if command -v gh > /dev/null; then
  eval "$(gh alias -s)"
fi

alias snv="svn"
alias vn="svn"
alias svnup="svn up"
alias svnst="svn st"
alias svnrevert="svn revert . --depth infinity"
alias sl="ls"
alias lls="ls"
alias gi="git"
alias gpush="git push origin"
alias cddot="cd ~/.dotfiles.git"

alias findhtml="find . -name '*.html'|xargs grep "
alias findpy="find . -name '*.py'|xargs grep "
alias findname="find . -name "
alias findsql="find . -name '*.sql'|xargs grep "
alias findjs='find . \( -path "node_modules" -o -path "static" \) -prune -o -name "*.js"|xargs grep '
alias findjson="find . -name '*.json'|xargs grep "
alias findcss="find . -name '*.css'|xargs grep "
alias rmpyc="find . -name '*.pyc'|xargs rm -rf"
alias rmsvn="find . -type d -name'*.svn'|xargs rm -rf"

alias cpmykey="ssh-copy-id -i ~/.ssh/private/wangnan_common.pub "

alias svim="sudoedit"
alias svi="sudoedit"

# create shell aliases for most used git commands
alias st='git st'
alias ci='git ci'
alias lg='git log'
alias co='git co'
alias br='git br'
alias dc='git diff --cached'

alias add='git add --all'
alias log='git log'
alias push='git push'
alias pull='git pull'
alias stash='git stash'
alias clone='git clone'
alias fetch='git fetch'
alias merge='git merge -s recursive -X patience'
alias branch='git branch'
alias rebase='git rebase'
alias amend='git commit -C HEAD --amend'
alias conn-fw='cd ~/.vpn/vpn_freeworld && sudo openvpn JP-04.ovpn'
alias conn-ks='cd ~/.vpn/vpn_kingsoft/config/ && sudo openvpn lugu.ovpn'

alias ..='cd ../'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'

alias yourt='yaourt'

alias zshrc="vim ~/.zshrc"
alias vimrc="vim ~/.vimrc"

# Pass aliases to root account
alias sudo='sudo '

if ls --color -d . &> /dev/null; then
  alias ls='ls --color=tty' || alias ls='ls -G'
fi

if ls --group-directories-first &> /dev/null; then
  eval "$(alias -L ls)' --group-directories-first'"
fi

eval "$(alias -L ls)' -h'"
