if [[ ! -d $HOME/.modules/antigen ]]; then
  git clone https://github.com/sheerun/antigen.git ~/.modules/antigen
fi

source ~/.modules/antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundles <<EOB
  pip
  python
  virtualenv
  rupa/z
  git
  safe-paste
  extract
  zsh-users/zsh-syntax-highlighting
  zsh-users/zaw
  zsh-users/zsh-completions
EOB

antigen theme robbyrussell/oh-my-zsh themes/candy

antigen apply

export EDITOR=vim

# Less
export LESSSECURE=1

fpath=(~/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-completions.git/src $fpath)

bindkey '^R' zaw-history
bindkey '^O' zaw-git-files-legacy

autoload -U zmv

# Readline
export WORDCHARS='*?[]~&;!$%^<>'

export LANG="zh_CN.UTF-8"

source ~/.dotfiles.git/zshconfig/zstyle
source ~/.dotfiles.git/zshconfig/zalias
source ~/.dotfiles.git/zshconfig/zfunction
