if [[ ! -d $HOME/.modules/antigen ]]; then
  git clone https://github.com/sheerun/antigen.git ~/.modules/antigen
fi

source ~/.modules/antigen/antigen.zsh

antigen use oh-my-zsh
antigen theme robbyrussell/oh-my-zsh themes/candy

antigen bundles <<EOB
  pip
  python
  virtualenvwrapper
  rupa/z
  git
  robertzk/send.zsh
  safe-paste
  extract
  zsh-users/zsh-syntax-highlighting
  zsh-users/zaw
  zsh-users/zsh-completions
EOB

antigen apply

export EDITOR=vim

# Less
export LESSSECURE=1

fpath=(~/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-completions.git/src $fpath)

bindkey '^R' zaw-history
bindkey '^O' zaw-git-files-legacy

autoload -U zmv

# Readline
export WORDCHARS='*?[]~&;!$%^<>'

export LANG="zh_CN.UTF-8"
export LC_ALL="zh_CN.UTF-8"
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
eval "$(pyenv init -)"

source ~/.dotfiles.git/zshconfig/zstyle
source ~/.dotfiles.git/zshconfig/zalias
source ~/.dotfiles.git/zshconfig/zfunction
